### ISSUE TITLE
Please not suggest replacing default python interpreter

### ISSUE THREAD

**Issue by martyanov** [nsingla/dbdiagrams#3]
Replacing default `python`, as stated in `README`, may lead to severe system breakage. Just use `#!/usr/bin/env python3` shebang or package the app.

**Comment by nsingla** [comment]
thanks for the suggestion, agreed - in case there are other apps or processes that use python2 - it can cause harm for sure.

Updated ```README``` 

Any pointer to a tutorial on how to package?

I was thinking because of python versioning issues, may be I should add a docker image, that vs. package - what's efficient in your opinion?

**Comment by martyanov** [comment]
I think plain Python packaging is your simplest and safest option. Also, you can write some tests and setup CI intergration to test against different Python versions.

Please, follow the guide - https://packaging.python.org/tutorials/packaging-projects/.

**Comment by nsingla** [comment]
very helpful, i will take a look. appreciate it.
